name: CI
on:
  push:

defaults:
  run:
    shell: bash

env:
  RG_VERSION: 15.1.0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: df -h
      - run: sudo apt-get -o DPkg::Lock::Timeout=60 -qq remove -y --fix-missing azure-cli google-chrome-stable microsoft-edge-stable powershell '^aspnetcore-.*' '^dotnet-.*' '^llvm-.*' '^mongodb-.*' '^temurin-.*-jdk' 'buildah' 'firefox' 'google-cloud-cli' 'google-cloud-sdk' 'kubectl' 'libgl1-mesa-dri' 'mono-devel' 'php.*' 'podman' 'skopeo'
