name: CI
on:
  push:

defaults:
  run:
    shell: bash

env:
  RG_VERSION: 15.1.0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: sudo apt-get -qq remove -y --fix-missing azure-cli
