name: CI
on:
  push:

defaults:
  run:
    shell: bash

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: cargo fetch

  test2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: cargo fetch

  test3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: cargo fetch

  test4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: cargo fetch

  test5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: cargo fetch

  test6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: cargo fetch

  test7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: cargo fetch
